import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiFetch } from './lib/api';
import PurchaseWorkspaceNav from './PurchaseWorkspaceNav';

type Account={id:string;code:string;name:string;accountType:string;parentId?:string|null;parentCode?:string|null;parentName?:string|null;isActive:boolean;isSystem:boolean};
type Entry={id:string;entryNumber:string;entryDate:string;sourceType:string;description:string;status:string;debit:string|number;credit:string|number};
type Settings={inventoryAccountId?:string|null;inputVatAccountId?:string|null;accountsPayableAccountId?:string|null;cashBankAccountId?:string|null;accountsReceivableAccountId?:string|null;revenueAccountId?:string|null;outputVatAccountId?:string|null;costOfSalesAccountId?:string|null};
const typeLabels:Record<string,string>={asset:'أصول',liability:'التزامات',equity:'حقوق ملكية',revenue:'إيرادات',expense:'مصروفات'};

export default function Accounting(){
 const [tab,setTab]=useState<'accounts'|'journals'|'reports'|'settings'>('accounts');
 const [report,setReport]=useState<'trial'|'income'|'balance'>('trial');
 const [reportRows,setReportRows]=useState<any[]>([]);
 const [accounts,setAccounts]=useState<Account[]>([]); const [entries,setEntries]=useState<Entry[]>([]);
 const [settings,setSettings]=useState<Settings>({}); const [form,setForm]=useState({code:'',name:'',accountType:'asset',parentId:''});
 const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false); const [from,setFrom]=useState(new Date(new Date().getFullYear(),0,1).toISOString().slice(0,10)); const [to,setTo]=useState(new Date().toISOString().slice(0,10));
 async function load(){try{const [a,j,s]=await Promise.all([apiFetch<{accounts:Account[]}>('/accounting/accounts'),apiFetch<{entries:Entry[]}>('/accounting/journal-entries'),apiFetch<{settings:Settings|null}>('/accounting/settings')]);setAccounts(a.accounts);setEntries(j.entries);setSettings(s.settings??{});}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المحاسبة');}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(tab==='reports')void loadReport(report)},[tab,report,from,to]);
 async function loadReport(kind:'trial'|'income'|'balance'){setError('');try{const path=kind==='trial'?'/accounting/reports/trial-balance':kind==='income'?'/accounting/reports/income-statement':'/accounting/reports/balance-sheet';const r=await apiFetch<{accounts:any[]}>(path+'?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to));setReportRows(r.accounts);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل التقرير');}}
 async function createAccount(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{await apiFetch('/accounting/accounts',{method:'POST',body:JSON.stringify({...form,parentId:form.parentId||null})});setForm({code:'',name:'',accountType:'asset',parentId:''});setMessage('تم إنشاء الحساب');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الحساب');}finally{setSaving(false);}}
 async function saveSettings(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{await apiFetch('/accounting/settings',{method:'POST',body:JSON.stringify(settings)});setMessage('تم حفظ إعدادات الترحيل المحاسبي');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الإعدادات');}finally{setSaving(false);}}
 const accountOptions=accounts.filter(a=>a.isActive);
 return <div className="odoo-workspace"><PurchaseWorkspaceNav/><main className="odoo-workspace-main">
  <header className="app-header"><div><span className="eyebrow">المحاسبة</span><h1>المحاسبة</h1><p>دليل الحسابات والقيود وتهيئة الترحيل.</p></div><Link className="secondary-button" to="/admin/dashboard">لوحة الإدارة</Link></header>
  {error&&<div className="info-strip warning">{error}</div>}{message&&<div className="info-strip">{message}</div>}
  <div className="portal-choice-actions"><button type="button" className={tab==='accounts'?'secondary-button active':'secondary-button'} onClick={()=>setTab('accounts')}>دليل الحسابات</button><button type="button" className={tab==='journals'?'secondary-button active':'secondary-button'} onClick={()=>setTab('journals')}>القيود اليومية</button><button type="button" className={tab==='reports'?'secondary-button active':'secondary-button'} onClick={()=>setTab('reports')}>التقارير المالية</button><button type="button" className={tab==='settings'?'secondary-button active':'secondary-button'} onClick={()=>setTab('settings')}>إعدادات الترحيل</button></div>
  {tab==='accounts'&&<section className="staff-management-grid"><section className="panel"><p className="eyebrow">دليل الحسابات</p><h2>إضافة حساب</h2><form className="form-stack" onSubmit={createAccount}><label>رقم الحساب<input dir="ltr" value={form.code} onChange={e=>setForm(v=>({...v,code:e.target.value}))} required/></label><label>اسم الحساب<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} required/></label><label>نوع الحساب<select value={form.accountType} onChange={e=>setForm(v=>({...v,accountType:e.target.value}))}>{Object.entries(typeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>الحساب الأب<select value={form.parentId} onChange={e=>setForm(v=>({...v,parentId:e.target.value}))}><option value="">بدون</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="primary-action button" disabled={saving}>{saving?'جارٍ الحفظ...':'إنشاء الحساب'}</button></form></section><section className="panel"><p className="eyebrow">الحسابات</p><h2>دليل الحسابات</h2>{!accounts.length?<p className="empty-state">لا توجد حسابات. أنشئ دليل الحسابات الخاص بالمركز أولًا.</p>:<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>رقم</th><th>الحساب</th><th>النوع</th><th>الأب</th><th>الحالة</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td dir="ltr">{a.code}</td><td><strong>{a.name}</strong>{a.isSystem&&<small>حساب نظام</small>}</td><td>{typeLabels[a.accountType]??a.accountType}</td><td>{a.parentCode?a.parentCode+' — '+a.parentName:'—'}</td><td>{a.isActive?'نشط':'غير نشط'}</td></tr>)}</tbody></table></div>}</section></section>}
  {tab==='journals'&&<section className="panel"><div className="panel-heading-row"><div><p className="eyebrow">القيود اليومية</p><h2>القيود اليومية</h2></div><button type="button" className="secondary-button" onClick={()=>void load()}>تحديث</button></div>{!entries.length?<p className="empty-state">لا توجد قيود مرحّلة بعد. بعد تهيئة الحسابات، ترحيل فاتورة مورد أو دفعة سينشئ القيد تلقائيًا.</p>:<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>رقم القيد</th><th>التاريخ</th><th>المصدر</th><th>البيان</th><th>مدين</th><th>دائن</th></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td dir="ltr">{x.entryNumber}</td><td>{String(x.entryDate)}</td><td>{x.sourceType==='purchase_bill'?'فاتورة مورد':x.sourceType==='purchase_payment'?'دفعة مورد':x.sourceType}</td><td>{x.description}</td><td>{Number(x.debit).toFixed(2)}</td><td>{Number(x.credit).toFixed(2)}</td></tr>)}</tbody></table></div>}</section>}
  {tab==='reports'&&<section className="panel"><div className="panel-heading-row"><div><p className="eyebrow">التقارير المالية</p><h2>التقارير المالية</h2><p>التقارير مبنية على القيود المرحّلة فقط.</p></div><div className="form-row"><label>من<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="button" className="secondary-button" onClick={()=>void loadReport(report)}>تحديث</button></div></div><div className="portal-choice-actions"><button type="button" className={report==='trial'?'secondary-button active':'secondary-button'} onClick={()=>setReport('trial')}>ميزان المراجعة</button><button type="button" className={report==='income'?'secondary-button active':'secondary-button'} onClick={()=>setReport('income')}>قائمة الدخل</button><button type="button" className={report==='balance'?'secondary-button active':'secondary-button'} onClick={()=>setReport('balance')}>المركز المالي</button></div>{!reportRows.length?<p className="empty-state">لا توجد قيود مرحّلة لعرضها في التقرير.</p>:<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>رقم الحساب</th><th>الحساب</th><th>النوع</th><th>مدين</th><th>دائن</th><th>الرصيد</th></tr></thead><tbody>{reportRows.map((x:any)=>{const d=Number(x.debit),cr=Number(x.credit);const balance=(x.accountType==='asset'||x.accountType==='expense'?d-cr:cr-d);return <tr key={x.id}><td dir="ltr">{x.code}</td><td><strong>{x.name}</strong></td><td>{typeLabels[x.accountType]??x.accountType}</td><td>{d.toFixed(2)}</td><td>{cr.toFixed(2)}</td><td>{balance.toFixed(2)}</td></tr>})}</tbody></table></div>}</section>}
  {tab==='settings'&&<section className="panel"><p className="eyebrow">إعدادات الترحيل</p><h2>إعدادات الترحيل</h2><p>الحسابات التالية تحدد ترحيل فواتير الموردين ومدفوعاتهم. لا يتم افتراض دليل حسابات أو نسبة ضريبة تلقائيًا.</p><form className="form-stack" onSubmit={saveSettings}><label>حساب المخزون / المشتريات<select value={settings.inventoryAccountId??''} onChange={e=>setSettings(v=>({...v,inventoryAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب ضريبة القيمة المضافة — مدخلات<select value={settings.inputVatAccountId??''} onChange={e=>setSettings(v=>({...v,inputVatAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب الدائنين / الموردين<select value={settings.accountsPayableAccountId??''} onChange={e=>setSettings(v=>({...v,accountsPayableAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب النقدية / البنك<select value={settings.cashBankAccountId??''} onChange={e=>setSettings(v=>({...v,cashBankAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب العملاء / الذمم المدينة<select value={settings.accountsReceivableAccountId??''} onChange={e=>setSettings(v=>({...v,accountsReceivableAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب الإيرادات<select value={settings.revenueAccountId??''} onChange={e=>setSettings(v=>({...v,revenueAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب ضريبة القيمة المضافة — مخرجات<select value={settings.outputVatAccountId??''} onChange={e=>setSettings(v=>({...v,outputVatAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب تكلفة المبيعات<select value={settings.costOfSalesAccountId??''} onChange={e=>setSettings(v=>({...v,costOfSalesAccountId:e.target.value||null}))}><option value="">اختر الحساب</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="primary-action button" disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ إعدادات الترحيل'}</button></form></section>}
 </main></div>;
}
