import { FormEvent, useEffect, useState } from 'react';
import { apiFetch } from './lib/api';

type User={id:string;staffType?:string|null;permissions?:string[]};
type Customer={id:string;name:string;lastName:string;customerNumber:string};
type Specialist={id:string;name:string;staffType:string};
type Exercise={id:string;exerciseName:string;sets?:number|null;repetitions?:number|null;durationSeconds?:number|null;restSeconds?:number|null;targetNotes?:string|null;sortOrder:number};
type Plan={id:string;customerId:string;specialistId:string;title:string;goals?:string|null;startDate:string;endDate?:string|null;status:string;version:number;customerName:string;customerLastName:string;specialistName:string;exercises:Exercise[]};

export default function FitnessManagement({user}:{user:User}){
 const isAdmin=user.staffType==='admin';const can=(p:string)=>isAdmin||(user.permissions??[]).includes(p);const canWrite=can('fitness.write');const statusLabel:Record<string,string>={draft:'مسودة',active:'نشطة',completed:'مكتملة',cancelled:'ملغاة'};const staffTypeLabel:Record<string,string>={admin:'إدارة',doctor:'طبيب',nutritionist:'أخصائي تغذية',trainer:'مدرب',employee:'موظف',cashier:'كاشير',warehouse:'مخازن'};
 const [plans,setPlans]=useState<Plan[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[specialists,setSpecialists]=useState<Specialist[]>([]),[selectedId,setSelectedId]=useState('');
 const [form,setForm]=useState({customerId:'',specialistId:'',title:'',goals:'',startDate:new Date().toISOString().slice(0,10),endDate:'',status:'draft'});
 const [exercise,setExercise]=useState({exerciseName:'',sets:'',repetitions:'',durationSeconds:'',restSeconds:'',targetNotes:''});
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const [planSearch,setPlanSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all');
 async function load(){try{const[p,o]=await Promise.all([apiFetch<{plans:Plan[]}>('/fitness'),apiFetch<{customers:Customer[];specialists:Specialist[]}>('/fitness/options')]);setPlans(p.plans);setCustomers(o.customers);setSpecialists(o.specialists);if(!form.customerId&&o.customers[0])setForm(v=>({...v,customerId:o.customers[0].id}));const currentSpecialist=o.specialists.find(x=>x.id===user.id);if(currentSpecialist)setForm(v=>({...v,specialistId:currentSpecialist.id}));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الخطط الرياضية');}}
 useEffect(()=>{void load()},[]);
 async function createPlan(e:FormEvent){e.preventDefault();if(!canWrite)return;setSaving(true);setError('');try{const r=await apiFetch<{plan:Plan}>('/fitness',{method:'POST',body:JSON.stringify({...form,endDate:form.endDate||null})});setSelectedId(r.plan.id);setMessage('تم إنشاء الخطة الرياضية');setForm(v=>({...v,title:'',goals:'',endDate:'',status:'draft'}));await load();}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الخطة');}finally{setSaving(false);}}
 async function addExercise(e:FormEvent){e.preventDefault();if(!canWrite||!selectedId)return;setSaving(true);setError('');try{const body={...exercise,sets:exercise.sets||null,repetitions:exercise.repetitions||null,durationSeconds:exercise.durationSeconds||null,restSeconds:exercise.restSeconds||null,sortOrder:plans.find(p=>p.id===selectedId)?.exercises.length??0};await apiFetch('/fitness/'+selectedId+'/exercises',{method:'POST',body:JSON.stringify(body)});setExercise({exerciseName:'',sets:'',repetitions:'',durationSeconds:'',restSeconds:'',targetNotes:''});setMessage('تمت إضافة التمرين');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر إضافة التمرين');}finally{setSaving(false);}}
 async function deleteExercise(id:string){if(!canWrite||!selectedId)return;try{await apiFetch('/fitness/'+selectedId+'/exercises/'+id,{method:'DELETE'});setMessage('تم حذف التمرين');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر حذف التمرين');}}
 const filteredPlans=plans.filter(p=>{const q=planSearch.trim().toLowerCase();return (statusFilter==='all'||p.status===statusFilter)&&(!q||(p.title+' '+p.customerName+' '+p.customerLastName+' '+p.specialistName).toLowerCase().includes(q));});
 const planKpis=[['إجمالي الخطط',plans.length],['مسودة',plans.filter(p=>p.status==='draft').length],['نشطة',plans.filter(p=>p.status==='active').length],['مكتملة',plans.filter(p=>p.status==='completed').length]] as const;
 const selected=plans.find(p=>p.id===selectedId);
 return <main className="app-shell"><header className="app-header"><div><span className="eyebrow">اللياقة</span><h1>الخطط الرياضية</h1></div></header>
 {error&&<div className="info-strip warning">{error}</div>}{message&&<div className="info-strip">{message}</div>}
 <section className="staff-management-grid"><section className="panel"><p className="eyebrow">خطة جديدة</p><h2>إنشاء خطة</h2><form className="form-stack" onSubmit={createPlan}>
 <label>العميل<select required disabled={!canWrite} value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}>{customers.map(x=><option key={x.id} value={x.id}>{x.customerNumber} — {x.name} {x.lastName}</option>)}</select></label>
 <label>الأخصائي<input required readOnly value={specialists.find(x=>x.id===form.specialistId)?.name??''} placeholder="سيتم تعيين الأخصائي من الحساب الحالي" /></label>
 <label>اسم الخطة<input required disabled={!canWrite} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="خطة اللياقة — المرحلة الأولى"/></label>
 <label>الهدف<textarea disabled={!canWrite} value={form.goals} onChange={e=>setForm({...form,goals:e.target.value})}/></label>
 <div className="form-row"><label>تاريخ البداية<input type="date" required disabled={!canWrite} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>تاريخ النهاية<input type="date" disabled={!canWrite} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div>
 <label>الحالة<select disabled={!canWrite} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">مسودة</option><option value="active">نشطة</option><option value="completed">مكتملة</option><option value="cancelled">ملغاة</option></select></label>
 {canWrite&&<button className="primary-action button" disabled={saving}>{saving?'جارٍ الحفظ...':'إنشاء الخطة'}</button>}</form></section>
 <section className="panel"><div className="panel-heading-row"><div><p className="eyebrow">الخطط</p><h2>الخطط الحالية</h2></div><button className="secondary-button" onClick={()=>void load()}>تحديث</button></div>
        <div className="erp-kpi-strip">{planKpis.map(([label,value])=><div className="erp-kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
        <div className="module-toolbar"><div className="toolbar-filters"><input value={planSearch} onChange={e=>setPlanSearch(e.target.value)} placeholder="بحث باسم الخطة أو العميل أو المدرب"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">كل الحالات</option>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
        {!filteredPlans.length?<p className="empty-state">لا توجد خطط مطابقة.</p>:<div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>الخطة</th><th>العميل</th><th>المدرب</th><th>البداية</th><th>الحالة</th><th></th></tr></thead><tbody>{filteredPlans.map(p=><tr key={p.id}><td>{p.title} <small>الإصدار {p.version}</small></td><td>{p.customerName} {p.customerLastName}</td><td>{p.specialistName}</td><td>{p.startDate}</td><td>{statusLabel[p.status]??p.status}</td><td><button className="secondary-button" onClick={()=>setSelectedId(p.id)}>فتح</button></td></tr>)}</tbody></table></div>}</section></section>
 {selected&&<section className="panel"><div className="panel-heading-row"><div><p className="eyebrow">تفاصيل الخطة</p><h2>{selected.title}</h2><p>{selected.customerName} {selected.customerLastName} · {selected.specialistName}</p></div></div>
 <div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>التمرين</th><th>المجموعات</th><th>التكرارات</th><th>المدة</th><th>الراحة</th><th></th></tr></thead><tbody>{selected.exercises.map(x=><tr key={x.id}><td>{x.exerciseName}</td><td>{x.sets??'—'}</td><td>{x.repetitions??'—'}</td><td>{x.durationSeconds?x.durationSeconds+' ث':'—'}</td><td>{x.restSeconds?x.restSeconds+' ث':'—'}</td><td>{canWrite&&<button className="secondary-button" onClick={()=>void deleteExercise(x.id)}>حذف</button>}</td></tr>)}</tbody></table></div>
 {canWrite&&<form className="form-stack" onSubmit={addExercise} style={{marginTop:16}}><h3>إضافة تمرين</h3><label>اسم التمرين<input required value={exercise.exerciseName} onChange={e=>setExercise({...exercise,exerciseName:e.target.value})} placeholder="المشي السريع"/></label><div className="form-row"><label>المجموعات<input type="number" min="0" value={exercise.sets} onChange={e=>setExercise({...exercise,sets:e.target.value})}/></label><label>التكرارات<input type="number" min="0" value={exercise.repetitions} onChange={e=>setExercise({...exercise,repetitions:e.target.value})}/></label><label>المدة بالثواني<input type="number" min="0" value={exercise.durationSeconds} onChange={e=>setExercise({...exercise,durationSeconds:e.target.value})}/></label><label>الراحة بالثواني<input type="number" min="0" value={exercise.restSeconds} onChange={e=>setExercise({...exercise,restSeconds:e.target.value})}/></label></div><label>ملاحظات الأداء<textarea value={exercise.targetNotes} onChange={e=>setExercise({...exercise,targetNotes:e.target.value})}/></label><button className="primary-action button" disabled={saving}>{saving?'جارٍ الحفظ...':'إضافة التمرين'}</button></form>}
 </section>}</main>;
}
