import { and, asc, desc, eq } from 'drizzle-orm';
import { Hono } from 'hono';
import { z } from 'zod';
import { requirePermission } from '../auth/permissions';
import { withDatabase } from '../db/client';
import { customers, measurementRecords, measurementTypes } from '../db/schema';

export type MeasurementBindings={HYPERDRIVE?:{connectionString:string};DATABASE_URL?:string};
export const measurementRoutes=new Hono<{Bindings:MeasurementBindings}>();
async function auth(c:any,permission:'customers.read'|'nutrition.write'|'measurements.read'|'measurements.write'){
 const result=await requirePermission(c,permission);
 if('error' in result)return result;
 if(!result.user.centerId)return {error:c.json({error:{code:'CENTER_REQUIRED',message:'الحساب غير مرتبط بمركز'}},403)};
 return result;
}
const schema=z.object({customerId:z.string().uuid(),measurementTypeId:z.string().uuid(),value:z.coerce.number().finite(),measuredAt:z.string().datetime({offset:true}).optional(),notes:z.string().trim().max(2000).optional().nullable()});
measurementRoutes.get('/types',async c=>{const a=await auth(c,'measurements.read');if('error'in a)return a.error;const rows=await withDatabase(c.env,db=>db.select().from(measurementTypes).where(and(eq(measurementTypes.centerId,a.user.centerId!),eq(measurementTypes.active,true))).orderBy(asc(measurementTypes.name)));return c.json({types:rows});});
measurementRoutes.get('/',async c=>{const a=await auth(c,'measurements.read');if('error'in a)return a.error;const customerId=c.req.query('customerId');const where=customerId?and(eq(measurementRecords.centerId,a.user.centerId!),eq(measurementRecords.customerId,customerId)):eq(measurementRecords.centerId,a.user.centerId!);const rows=await withDatabase(c.env,db=>db.select({id:measurementRecords.id,customerId:measurementRecords.customerId,value:measurementRecords.value,measuredAt:measurementRecords.measuredAt,notes:measurementRecords.notes,typeId:measurementTypes.id,typeCode:measurementTypes.code,typeName:measurementTypes.name,unit:measurementTypes.unit,customerName:customers.firstName,customerLastName:customers.lastName}).from(measurementRecords).innerJoin(measurementTypes,eq(measurementTypes.id,measurementRecords.measurementTypeId)).innerJoin(customers,eq(customers.id,measurementRecords.customerId)).where(where).orderBy(desc(measurementRecords.measuredAt)).limit(500));return c.json({measurements:rows});});
measurementRoutes.post('/',async c=>{const a=await auth(c,'measurements.write');if('error'in a)return a.error;const parsed=schema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json({error:{code:'INVALID_INPUT',message:parsed.error.issues[0]?.message??'بيانات القياس غير صحيحة'}},400);const d=parsed.data;const result=await withDatabase(c.env,db=>db.transaction(async tx=>{const [customer]=await tx.select({id:customers.id}).from(customers).where(and(eq(customers.id,d.customerId),eq(customers.centerId,a.user.centerId!))).limit(1);const [type]=await tx.select({id:measurementTypes.id}).from(measurementTypes).where(and(eq(measurementTypes.id,d.measurementTypeId),eq(measurementTypes.centerId,a.user.centerId!),eq(measurementTypes.active,true))).limit(1);if(!customer)return{error:'CUSTOMER_NOT_FOUND' as const};if(!type)return{error:'MEASUREMENT_TYPE_NOT_FOUND' as const};const [record]=await tx.insert(measurementRecords).values({centerId:a.user.centerId!,customerId:d.customerId,measurementTypeId:d.measurementTypeId,value:String(d.value),measuredAt:d.measuredAt?new Date(d.measuredAt):new Date(),notes:d.notes||null,createdBy:a.user.userId}).returning();return{record};}));if('error'in result)return c.json({error:{code:result.error,message:result.error==='CUSTOMER_NOT_FOUND'?'العميل غير موجود داخل هذا المركز':'نوع القياس غير موجود أو غير نشط'}},404);return c.json(result,201);});
measurementRoutes.delete('/:id',async c=>{const a=await auth(c,'measurements.write');if('error'in a)return a.error;const[row]=await withDatabase(c.env,db=>db.select({id:measurementRecords.id}).from(measurementRecords).where(and(eq(measurementRecords.id,c.req.param('id')),eq(measurementRecords.centerId,a.user.centerId!))).limit(1));if(!row)return c.json({error:{code:'MEASUREMENT_NOT_FOUND',message:'القياس غير موجود'}},404);await withDatabase(c.env,db=>db.delete(measurementRecords).where(eq(measurementRecords.id,row.id)));return c.json({ok:true});});